#!/bin/bash
#
# Ben Fasoli
#
# Convenience script to ensure code is fetched from different sources and
# fortran binaries and DLLs are compiled and moved to the correct location

set -e

# Check if ./setup is run from the top level of the project
dircnt=$(ls -d */ | grep -x -e exe/ -e r/ | wc -l)
if [ $dircnt -lt 2 ]; then
  echo "./setup must be run from the top level directory of the STILT project" > /dev/stderr
  exit 1
fi

# Check dependency versions
if ! command -v Rscript &> /dev/null; then
  echo "Rscript not found" > /dev/stderr
  exit 1
fi

if ! command -v bc &> /dev/null; then
  echo "bc not found, continuing without checking R version"
else
  R_VERSION=$(Rscript --version &> /dev/stdout | cut -d " " -f 5 | cut -d "." -f 1-2)
  if (( $(echo "$R_VERSION <= 3.5" | bc -l > /dev/null) )); then
    echo "R version $R_VERSION must be 3.5 or higher" > /dev/stderr
    exit 1
  fi
fi

if ! command -v nc-config &> /dev/null; then
  echo "NetCDF library (nc-config) not found" > /dev/stderr
  exit 1
fi

NC_VERSION=$(nc-config --version | cut -d " " -f 2 | cut -d "." -f 1)
if [ "$NC_VERSION" -lt 4 ]; then
  echo "NetCDF library (nc-config) version must be 4.0 or higher" > /dev/stderr
  exit 1
fi

# Compile permute DLL for footprint kernel aggregation
echo "Compiling footprint kernel aggregation subroutine..."
R CMD SHLIB r/src/permute.f90
if [ ! -s r/src/permute.so ]; then
  echo "Problem compiling r/src/permute.so." > /dev/stderr
  exit 1
fi

# Prompt user for binary/compile installation
if [ -z $1 ]; then
  echo "
  STILT hymodelc installation options:
  1 - Compile hymodelc from source
  2 - hymodelc-linux-x64
  3 - hymodelc-macos-x64
  "
  echo -n "Install option (number from above): "
  read -n 1 install
  echo
else
  install=$1
fi

if [[ $install -eq 1 ]]; then
  # Prompt user for jena SVN username
  echo "
  STILT is built on top of the HYSPLIT model. Registration is required to access
  the fortran trajectory calculations.

  Registration: https://mail.bgc-jena.mpg.de/mailman/listinfo/stilt_user
  Username is email prefix: user@email.com -> user
  Password is sent to your email address after registration
  "
  echo -n "Username: "
  read username
  if [ -z $username ]; then
    echo "No username input. Exiting."
    exit 1
  fi
  # Checkout merged_stilt_hysplit contents into fortran/
  # Compilers prioritize fortran/makefile over fortran/Makefile
  svn --username $username checkout \
    https://projects.bgc-jena.mpg.de/STILT/svn/trunk/merged_stilt_hysplit/ \
    fortran/
  # Compile STILT trajectory calculation binary
  echo "Compiling STILT trajectory calculation binary (hymodelc)..."
  sed -i.bak -e 's/FC =.*/FC = gfortran/' fortran/Makefile
	sed -i.bak -e 's/CFLAGS =.*/CFLAGS = $(GFOR)/' fortran/Makefile
  make -C fortran
  if [ ! -s fortran/hymodelc ]; then
    echo "Problem compiling fortran/hymodelc."
    echo "You may need to edit settings in fortran/makefile to compile manually."
    exit 1
  fi
  
  # Move hymodelc to shared exe/ directory
  mv fortran/hymodelc exe/hymodelc

# Fetch binary from GitHub release
elif [[ $install -eq 2 ]]; then
  wget -O exe/hymodelc \
    https://github.com/uataq/stilt/releases/download/v1.2/hymodelc-linux-x64
elif [[ $install -eq 3 ]]; then
  wget -O exe/hymodelc \
    https://github.com/uataq/stilt/releases/download/v1.2/hymodelc-macos-x64
else
  echo "Invalid install option."
  exit 1
fi

# Check that hymodelc was created from methods above
if [ ! -s exe/hymodelc ]; then
  echo "Problem creating hymodelc."
  exit 1
fi

# Ensure hymodelc, run_stilt.r, and stilt_cli.r are executable
chmod +x exe/hymodelc r/run_stilt.r r/stilt_cli.r


echo "
STILT installation successful.

Relevant manuscripts:
1. Fasoli, B., Lin, J. C., Bowling, D. R., Mitchell, L., and Mendoza, D.: 
   Simulating atmospheric tracer concentrations for spatially distributed 
   receptors: updates to the Stochastic Time-Inverted Lagrangian Transport 
   model's R interface (STILT-R version 2), Geosci. Model Dev., 11, 2813-2824, 
   [10.5194/gmd-11-2813-2018](https://doi.org/10.5194/gmd-11-2813-2018), 2018.
2. Lin, J. C., Gerbig, C., Wofsy, S. C., Andrews, A. E., Daube, B. C., Davis,
   K. J. and Grainger, C. A.: A near-field tool for simulating the upstream 
   influence of atmospheric observations: The Stochastic Time-Inverted Lagrangian
   Transport (STILT) model, J. Geophys. Res., 108(D16), ACH 2-1-ACH 2-17, 
   [10.1029/2002JD003161](https://doi.org/10.1029/2002JD003161), 2003.

We strongly suggest you subscribe to the mailing list at
https://uataq.github.io/stilt/
to be notified of critical code updates.
"
