read.asc<-function(file){
#Facilitates importing files generated by SAS, which are blank-separated values
#  and may contain '.' as symbol for NAs
#4/1/2000 by JCL
#
#  $Id: read.asc.r,v 1.2 2007-06-27 11:54:03 skoerner Exp $
#---------------------------------------------------------------------------------------------------

   #mat<-read.table(file=file,sep=",",na.string=".")  #read in data and create data frame
   #read header line that contains column names
   colnm <- scan(file = file, sep = " ", n = count.fields(file, sep = "")[1], what = "")
   mat <- scan(file = file, skip = 1, what = "")
   #scan in rest of file--first as VECTOR
   mat[mat == "."] <- "NA"
   #assign "NA"s to ".", which is default symbol for NA in SAS
   mat <- matrix(as.numeric(mat), byrow = T, ncol = length(colnm))
   dimnames(mat) <- list(NULL, colnm)
   return(mat)
}

