#' write_setup writes a SETUP.CFG namelist file to control the model behavior
#' @author Ben Fasoli
#'
#' SETUP.CFG contains namelist for controlling transport and dispersion behavior
#'
#' @export

write_setup <- function(varsiwant, 
                        capemin = -1,
                        cmass = 0,
                        conage = 48, 
                        cpack = 1, 
                        delt = 1, 
                        dxf = 1, 
                        dyf = 1, 
                        dzf = 0.01, 
                        efile = '',
                        frhmax = 3, 
                        frhs = 1, 
                        frme = 0.1,
                        frmr = 0, 
                        frts = 0.1, 
                        frvs = 0.1, 
                        hscale = 10800,
                        ichem = 8,
                        idsp = 2,
                        initd = 0, 
                        isot = -99, 
                        k10m = 1,
                        kagl = 1,
                        kbls = 1,
                        kblt = 5,
                        kdef = 1, 
                        khinp = 0,
                        khmax = 9999,
                        kmix0 = 150, 
                        kmixd = 3,
                        kmsl = 0,
                        kpuff = 0,
                        krand = 2,
                        krnd = 6,
                        kspl = 1, 
                        kwet = 1,
                        kzmix = 0,
                        maxdim = 1,
                        maxpar = 10000,
                        mgmin = 10, 
                        mhrs = 9999,
                        nbptyp = 1,
                        ncycl = 0,
                        ndump = 0, 
                        ninit = 1,
                        numpar = 100, 
                        nstr = 0,
                        nturb = 0,
                        nver = 0,
                        outdt = 0,
                        p10f = 1, 
                        pinbc = '',
                        pinpf = '',
                        poutf = '',
                        qcycle = 0,
                        rhb = 80,
                        rht = 60,
                        splitf = 1,
                        tkerd = 0.18, 
                        tkern = 0.18,
                        tlfrac = 0.1,
                        tout = 0,
                        tratio = 0.75,
                        tvmix = 1, 
                        veght = 0.5,
                        vscale = 200,
                        vscaleu = 200,
                        vscales = -1,
                        wbbh = 0,
                        wbwf = 0,
                        wbwr = 0,
                        wvert = FALSE,
                        winderrtf = 0,
                        zicontroltf = 0,
                        file = 'SETUP.CFG',
                        ...) {

  if (basename(file) != 'SETUP.CFG')
    stop('write_setup(): file argument must end with SETUP.CFG')

  ivmax <- length(varsiwant)
  varsiwant <- paste0('\'', paste(varsiwant, collapse = '\', \''), '\'')

  eq <- function(lhs, rhs) {
    paste0(lhs, '=', rhs, ',')
  }

  txt <- c('$SETUP',
           eq('CAPEMIN', capemin),
           eq('CMASS', cmass),
           eq('CONAGE', conage),
           eq('CPACK', cpack),
           eq('DELT', delt),
           eq('DXF', dxf),
           eq('DYF', dyf),
           eq('DZF', dzf),
           eq('EFILE', efile),
           eq('FRHMAX', frhmax),
           eq('FRHS', frhs),
           eq('FRME', frme),
           eq('FRMR', frmr),
           eq('FRTS', frts),
           eq('FRVS', frvs),
           eq('HSCALE', hscale),
           eq('ICHEM', ichem),
           eq('IDSP', idsp),
           eq('INITD', initd),
           eq('ISOT', isot),
           eq('IVMAX', ivmax),
           eq('K10M', k10m),
           eq('KAGL', kagl),
           eq('KBLS', kbls),
           eq('KBLT', kblt),
           eq('KDEF', kdef),
           eq('KHINP', khinp),
           eq('KHMAX', khmax),
           eq('KMIX0', kmix0),
           eq('KMIXD', kmixd),
           eq('KMSL', kmsl),
           eq('KPUFF', kpuff),
           eq('KRAND', krand),
           eq('KRND', krnd),
           eq('KSPL', kspl),
           eq('KWET', kwet),
           eq('KZMIX', kzmix),
           eq('MAXDIM', maxdim),
           eq('MAXPAR', maxpar),
           eq('MGMIN', mgmin),
           eq('MHRS', mhrs),
           eq('NBPTYP', nbptyp),
           eq('NCYCL', ncycl),
           eq('NDUMP', ndump),
           eq('NINIT', ninit),
           eq('NSTR', nstr),
           eq('NTURB', nturb),
           eq('NUMPAR', numpar),
           eq('NVER', nver),
           eq('OUTDT', outdt),
           eq('P10F', p10f),
           eq('PINBC', pinbc),
           eq('PINPF', pinpf),
           eq('POUTF', poutf),
           eq('QCYCLE', qcycle),
           eq('RHB', rhb),
           eq('RHT', rht),
           eq('SPLITF', splitf),
           eq('TKERD', tkerd),
           eq('TKERN', tkern),
           eq('TLFRAC', tlfrac),
           eq('TOUT', tout),
           eq('TRATIO', tratio),
           eq('TVMIX', tvmix),
           eq('VARSIWANT', varsiwant),
           eq('VEGHT', veght),
           eq('VSCALE', vscale),
           eq('VSCALEU', vscaleu),
           eq('VSCALES', vscales),
           eq('WBBH', wbbh),
           eq('WBWF', wbwf),
           eq('WBWR', wbwr),
           eq('WVERT', wvert),
           eq('WINDERRTF', winderrtf),
           eq('ZICONTROLTF', zicontroltf),
           '$END')

  write(txt, file)
  file
}
