
      SUBROUTINE CPOLLL (STRCMP, XLAT,XLONG, ENX,ENY,ENZ)
!*  WRITTEN ON 11/23/94 BY Dr. Albion Taylor  NOAA / OAR / ARL
      PARAMETER (PI=3.14159265358979,RADPDG=PI/180.,DGPRAD=180./PI)
      DOUBLE PRECISION XPOLG,YPOLG,ALONG,SLONG,CLONG,ROT
      REAL STRCMP(9)
      ALONG = CSPANF( XLONG - STRCMP(2), -180., 180.)
        ROT = - STRCMP(1) * ALONG
      SLONG = SIN( RADPDG * ROT )
      CLONG = COS( RADPDG * ROT )
      XPOLG = SLONG * STRCMP(5) + CLONG * STRCMP(6)
      YPOLG = CLONG * STRCMP(5) - SLONG * STRCMP(6)
      CLAT = COS(RADPDG * XLAT)
      ENX = CLAT * XPOLG
      ENY = CLAT * YPOLG
      ENZ = SIN(RADPDG * XLAT)
      RETURN
      END
