SUBROUTINE IERSET

  USE iercfg
  USE funits 

  LOGICAL FTEST
  NAMELIST /IERCHEM/ BO3,AO3,PSTB,RVOC,RISO,GAMMA,BETA

  INQUIRE(FILE='IERCHEM.CFG',EXIST=FTEST)
  IF(FTEST)THEN
     OPEN(KF33,FILE='IERCHEM.CFG')
     READ(KF33,IERCHEM)
     CLOSE(KF33)
     WRITE(*,*)' NOTICE   main: using IERCHEM.CFG namelist file'
  ELSE
     OPEN(KF33,FILE='ierchem.bak')
     WRITE(KF33,IERCHEM)
     CLOSE(KF33)
  END IF

END SUBROUTINE ierset
